// Supabase Edge Function: architect-verify-otp
// Verifies the OTP generated by architect-send-otp, then returns the
// architect profile so the frontend can complete login (same payload
// LoginPage.jsx used to pass straight to onLoginSuccess).
//
// Expected secrets:
//  - SUPABASE_URL
//  - SUPABASE_SERVICE_ROLE_KEY

import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from 'jsr:@supabase/supabase-js@2';

interface VerifyOtpRequest {
  mobile_number: string;
  otp: string;
  purpose?: string; // 'login' (default) or 'payout'
}

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

Deno.serve(async (req: Request) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders });
  }

  try {
    const { mobile_number, otp, purpose }: VerifyOtpRequest = await req.json();
    const cleanMobile = (mobile_number || '').trim();
    const cleanOtp = (otp || '').trim();
    const cleanPurpose = (purpose || 'login').trim();

    if (!cleanMobile || !cleanOtp) {
      return new Response(
        JSON.stringify({ success: false, error: 'Mobile number and OTP are required' }),
        { headers: { ...corsHeaders, 'Content-Type': 'application/json' }, status: 200 }
      );
    }

    const supabaseAdmin = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? '',
    );

    // Fetch the most recent unverified OTP record for this mobile number + purpose
    const { data: otpRecord, error: otpFetchError } = await supabaseAdmin
      .from('architect_otp_verifications')
      .select('*')
      .eq('mobile_number', cleanMobile)
      .eq('purpose', cleanPurpose)
      .eq('is_verified', false)
      .order('created_at', { ascending: false })
      .limit(1)
      .maybeSingle();

    if (otpFetchError) throw otpFetchError;

    if (!otpRecord) {
      return new Response(
        JSON.stringify({ success: false, error: 'No pending OTP found. Please request a new OTP.' }),
        { headers: { ...corsHeaders, 'Content-Type': 'application/json' }, status: 200 }
      );
    }

    if (new Date(otpRecord.expires_at) < new Date()) {
      return new Response(
        JSON.stringify({ success: false, error: 'OTP has expired. Please request a new OTP.' }),
        { headers: { ...corsHeaders, 'Content-Type': 'application/json' }, status: 200 }
      );
    }

    if (otpRecord.attempts >= otpRecord.max_attempts) {
      return new Response(
        JSON.stringify({ success: false, error: 'Too many incorrect attempts. Please request a new OTP.' }),
        { headers: { ...corsHeaders, 'Content-Type': 'application/json' }, status: 200 }
      );
    }

    if (otpRecord.otp !== cleanOtp) {
      await supabaseAdmin
        .from('architect_otp_verifications')
        .update({ attempts: otpRecord.attempts + 1 })
        .eq('id', otpRecord.id);

      return new Response(
        JSON.stringify({ success: false, error: 'Invalid OTP. Please try again.' }),
        { headers: { ...corsHeaders, 'Content-Type': 'application/json' }, status: 200 }
      );
    }

    // OTP correct — mark verified
    await supabaseAdmin
      .from('architect_otp_verifications')
      .update({ is_verified: true })
      .eq('id', otpRecord.id);

    if (cleanPurpose !== 'login') {
      // Non-login purposes (e.g. 'payout') just need confirmation that the
      // OTP was correct — no architect profile lookup or last_login touch.
      return new Response(
        JSON.stringify({ success: true }),
        { headers: { ...corsHeaders, 'Content-Type': 'application/json' }, status: 200 }
      );
    }

    // Re-fetch architect profile + update last_login (same as original login flow)
    const { data: architectData, error: architectError } = await supabaseAdmin
      .from('master_architect')
      .select('*')
      .eq('mobile_number', cleanMobile)
      .maybeSingle();

    if (architectError) throw architectError;

    if (!architectData) {
      return new Response(
        JSON.stringify({ success: false, error: 'Architect profile not found.' }),
        { headers: { ...corsHeaders, 'Content-Type': 'application/json' }, status: 200 }
      );
    }

    await supabaseAdmin
      .from('master_architect')
      .update({ last_login: new Date().toISOString() })
      .eq('mobile_number', cleanMobile);

    return new Response(
      JSON.stringify({ success: true, data: architectData }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' }, status: 200 }
    );

  } catch (error) {
    console.error('Unhandled error:', error);
    return new Response(
      JSON.stringify({ success: false, error: 'Internal server error' }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' }, status: 500 }
    );
  }
});
